# The benchmark: its generator, its inputs, and the runners that time the engine.
#
# A benchmark input is a *derivation*, so Nix knows it exists, rebuilds it when it is
# missing, and `nix store gc` can reclaim the gigabytes when nothing references them.
#
# It is specifically a *fixed-output* derivation, which is a stronger property and the
# one that matters at this size. A fixed-output derivation's store path is a function of
# its name and its `hash` — nothing else. Change the README, the engine, the flake, and
# the archive already in the store is still the archive Nix uses.
#
# Input-addressed derivations do not behave that way: their path covers every build
# input, which here transitively included the whole repository (the generator is built
# from it). That made the 3 GB archive regenerate on any tracked edit — and worst of all
# on `bench/history.jsonl`, which the runner below appends to at the end of every run.
# Benchmarking therefore invalidated the benchmark input, every single time.
{ pkgs, rust }:

let
  inherit (pkgs) lib;

  # Only what the generator actually compiles from. The engine's own source is in here
  # because cargo builds the library alongside the example, but tests, docs, the flake
  # and bench/history.jsonl are not — none of them can change a generated byte, and
  # every one of them used to force a rebuild.
  generatorSrc = lib.fileset.toSource {
    root = ../.;
    fileset = lib.fileset.unions [
      ../Cargo.toml
      ../Cargo.lock
      ../src
      ../examples
    ];
  };

  # The seeded generator, installed so an input can be built without a cargo checkout.
  generator = rust.rustPlatform.buildRustPackage {
    pname = "transaction-generator";
    version = "0.1.0";
    src = generatorSrc;
    inherit (rust) cargoLock;

    cargoBuildFlags = [
      "--example"
      "generate_transactions"
    ];
    doCheck = false;

    installPhase = ''
      runHook preInstall
      install -Dm755 \
        "$(find target -type f -name generate_transactions -perm -u+x | head -n1)" \
        "$out/bin/generate-transactions"
      runHook postInstall
    '';

    meta = {
      description = "Deterministic transaction-log generator for the benchmark";
      mainProgram = "generate-transactions";
    };
  };

  # generate -> tar -> xz, written once so the reproducibility check below exercises
  # byte-for-byte the same pipeline the pinned hashes were taken from.
  script = spec: dest: ''
    generate-transactions \
      --seed ${toString spec.seed} \
      ${lib.optionalString (spec.bytes != null) "--bytes ${spec.bytes}"} \
      ${lib.optionalString (spec.records != null) "--records ${toString spec.records}"} \
      --clients ${toString spec.clients} \
      --mix ${spec.mix} > transactions.csv

    # The thread count is fixed at 4 rather than -T0, and that is a correctness
    # requirement, not a tuning choice. xz's threaded encoder splits the stream into
    # independently compressed blocks; its single-threaded encoder does not, and the
    # two produce different bytes. -T0 means "one thread per core", so on a one-core
    # builder the archive would come out different and fail the hash below. Measured
    # on this input: -T2, -T3, -T4, -T8 and -T16 are byte-identical, -T1 is not.
    #
    # --block-size then pins the division explicitly instead of inheriting the value
    # xz derives from the preset, so an xz upgrade that changes that default cannot
    # silently invalidate the pinned hashes.
    XZ_OPT="-1 -T4 --block-size=16MiB" \
      tar --sort=name --mtime='@0' --owner=0 --group=0 --numeric-owner \
      -cJf ${dest} transactions.csv

    rm transactions.csv
  '';

  archiveName = spec: "transactions-${spec.mix}-${spec.tag}.tar.xz";

  archiveEnv = {
    nativeBuildInputs = [
      generator
      pkgs.gnutar
      pkgs.xz
    ];
  };

  defaults = {
    bytes = null;
    records = null;
    mix = "balanced";
    clients = 65535;
    seed = 20260816;
  };

  # A benchmark input, addressed by content. `hash` is mandatory: an input without one
  # is an input that regenerates itself behind your back. To add or change a profile,
  # set `hash = lib.fakeHash`, build it once, and copy the hash Nix reports as "got:".
  input =
    args:
    let
      spec = defaults // args;
    in
    pkgs.runCommand (archiveName spec) (
      archiveEnv
      // {
        outputHashAlgo = "sha256";
        outputHashMode = "flat";
        outputHash = spec.hash;
      }
    ) (script spec "$out");

  # The same archive built the ordinary way, so its store path — unlike the pinned one —
  # moves whenever the generator does. Comparing the two turns a stale hash into a build
  # failure that names itself, instead of a benchmark that quietly measures old data.
  rebuilt =
    args:
    let
      spec = defaults // args;
    in
    pkgs.runCommand "rebuilt-${archiveName spec}" archiveEnv (script spec "$out");

  smallSpec = {
    bytes = "16MiB";
    clients = 256;
    tag = "16MiB";
    hash = "sha256-3CiL7N/xriEURiUqL7MNp2+/6OXn0OdRTVUuh9PdiBE=";
  };
  largeSpec = {
    records = 100000000;
    tag = "100Mrec";
    hash = "sha256-SthK0pAT3d22G3jv13pYJ4dio7UPMgNK1VsKfNk/jZQ=";
  };
  settledSpec = largeSpec // {
    mix = "settled";
    hash = "sha256-szIhWIcwRsqaCRwsVyHZrjvCcGjuT7tD0CZXINFCSJ0=";
  };

  small = input smallSpec;
  large = input largeSpec;
  settled = input settledSpec;

  # Times the packaged engine — the same binary `nix build` produces, not whatever a
  # local cargo left in ./target — against a store-resident input.
  #
  # Every run appends a record to a history file (./bench/history.jsonl by default,
  # override with BENCH_HISTORY) and reports the delta against the previous run of the
  # same input, so a regression shows up as a number rather than a feeling.
  runner =
    { name, source }:
    pkgs.writeShellApplication {
      inherit name;
      runtimeInputs = with pkgs; [
        time
        coreutils
        gawk
        jq
        git
        gnutar
        xz
      ];
      text = ''
        input="${source}"
        history="''${BENCH_HISTORY:-bench/history.jsonl}"

        # Only the measurement artefacts are temporary, and they are cleaned up.
        work="$(mktemp -d)"
        trap 'rm -rf "$work"' EXIT

        archive_bytes="$(stat -L -c %s "$input")"
        read -r input_records input_bytes < <(tar -xOf "$input" | wc -l -c)
        input_records=$(( input_records - 1 ))

        printf '\n  input     %s uncompressed (%s compressed), %s records\n' \
          "$(numfmt --to=iec "$input_bytes")" "$(numfmt --to=iec "$archive_bytes")" "$input_records"
        printf '  from      %s\n' "$input"

        # %e wall, %U user, %S sys, %P cpu%, %M peak RSS KiB, %F major faults,
        # %R minor faults, %w voluntary switches, %c involuntary switches.
        tar -xOf "$input" | command time -o "$work/timing" -f '%e %U %S %P %M %F %R %w %c' \
          ${lib.getExe rust.transactionSolver} \
          > "$work/accounts.csv" 2> "$work/rejected.log"
        read -r wall user sys cpu rss majflt minflt volcsw involcsw < "$work/timing"
        cpu="''${cpu%\%}"

        accounts="$(( $(wc -l < "$work/accounts.csv") - 1 ))"
        rejected="$(wc -l < "$work/rejected.log")"
        output_sha="$(sha256sum "$work/accounts.csv" | cut -d' ' -f1)"

        # The trailing newline matters: `read` returns non-zero without a delimiter, and
        # this script runs under `set -e`.
        read -r rps mbps < <(awk -v b="$input_bytes" -v r="$input_records" -v e="$wall" \
          'BEGIN { if (e <= 0) e = 0.001; printf "%.0f %.1f\n", r / e, b / e / 1000000 }')

        printf '\n  wall      %s s\n' "$wall"
        printf '  cpu       %s s user, %s s sys (%s%% of one core)\n' "$user" "$sys" "$cpu"
        printf '  peak rss  %s\n' "$(numfmt --to=iec "$(( rss * 1024 ))")"
        printf '  faults    %s major, %s minor\n' "$majflt" "$minflt"
        printf '  switches  %s voluntary, %s involuntary\n' "$volcsw" "$involcsw"
        printf '  rate      %s records/s, %s MB/s\n' "$rps" "$mbps"
        printf '\n  accounts  %s\n' "$accounts"
        printf '  rejected  %s\n' "$rejected"
        printf '  output    sha256 %s\n' "''${output_sha:0:32}"

        # Compare against the last run over the same input before recording this one.
        previous=null
        if [[ -s "$history" ]]; then
          previous="$(jq -sc --arg i "$input" \
            '[.[] | select(.input == $i)] | last // null' "$history")"
        fi
        if [[ "$previous" != "null" ]]; then
          read -r prev_wall prev_rss <<< "$(jq -r '"\(.wall_s) \(.peak_rss_kb)"' <<< "$previous")"
          awk -v w="$wall" -v pw="$prev_wall" -v m="$rss" -v pm="$prev_rss" \
            'BEGIN { if (pw > 0 && pm > 0)
                       printf "\n  vs previous  wall %+.1f%%, peak rss %+.1f%%\n",
                              (w - pw) / pw * 100, (m - pm) / pm * 100 }'
        fi

        mkdir -p "$(dirname "$history")"
        jq -nc \
          --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          --arg commit "$(git rev-parse --short HEAD 2>/dev/null || echo unknown)" \
          --arg input "$input" \
          --arg output_sha256 "$output_sha" \
          --arg kernel "$(uname -r)" \
          --argjson cpus "$(nproc)" \
          --argjson input_bytes "$input_bytes" \
          --argjson records "$input_records" \
          --argjson wall_s "$wall" \
          --argjson user_s "$user" \
          --argjson sys_s "$sys" \
          --argjson cpu_pct "$cpu" \
          --argjson peak_rss_kb "$rss" \
          --argjson major_faults "$majflt" \
          --argjson minor_faults "$minflt" \
          --argjson voluntary_switches "$volcsw" \
          --argjson involuntary_switches "$involcsw" \
          --argjson records_per_s "$rps" \
          --argjson mb_per_s "$mbps" \
          --argjson accounts "$accounts" \
          --argjson rejected "$rejected" \
          '$ARGS.named' >> "$history"

        printf '  recorded  %s\n' "$history"
      '';
    };

  benchLarge = runner {
    name = "bench";
    source = large;
  };
  benchSmall = runner {
    name = "bench-small";
    source = small;
  };
  benchSettled = runner {
    name = "bench-settled";
    source = settled;
  };
in
{
  packages = {
    bench-generator = generator;
    bench-input = large;
    bench-input-small = small;
    bench-input-settled = settled;
  };

  apps = {
    bench = {
      type = "app";
      program = "${benchLarge}/bin/bench";
    };
    bench-small = {
      type = "app";
      program = "${benchSmall}/bin/bench-small";
    };
    bench-settled = {
      type = "app";
      program = "${benchSettled}/bin/bench-settled";
    };
  };

  # The pinned hashes are load-bearing: while they hold, the archives are never rebuilt,
  # which also means a changed generator would go unnoticed and the benchmark would keep
  # measuring superseded data. This check is the counterweight — it is input-addressed,
  # so it re-runs whenever the generator changes, and it fails if 16 MiB of freshly
  # generated archive no longer matches the pinned one.
  checks.bench-input-reproducible = pkgs.runCommand "check-bench-input-reproducible" { } ''
    if ! cmp -s ${rebuilt smallSpec} ${small}; then
      echo "the generator no longer reproduces the pinned benchmark inputs." >&2
      echo "regenerate and update the hashes in nix/bench.nix." >&2
      exit 1
    fi
    touch $out
  '';
}
